/*----- constants -----*/
const startButton = document.querySelector('button');
const colors = document.querySelectorAll('.tile');

console.log(colors);
const scoreCounter = document.querySelector('input');
const flash = board => {

}
const timeout = ''


/*----- state variables -----*/
let score = 0;
let turnNumber


let sequence = [
    getRandomColor(),
    getRandomColor(),
    getRandomColor(),
    getRandomColor()
];

console.log(sequence);

let anotherColor = [
    "lightPink",
    "skyBlue",
    "lightYellow",
    "lightGreen"
];



/*----- event listeners -----*/
//start button  click
startButton.addEventListener('click', startGame);

//end game
//instruction click 


/*----- functions -----*/
//Next level
// Initialize the game
function startGame() {
    console.log('testStart');
    colors[0].style.backgroundColor = "red"; 
    colors[1].style.backgroundColor = "blue";
    colors[2].style.backgroundColor = "yellow";
    colors[3].style.backgroundColor = "green"; 
    turn = 4;
    flashColor() 
    //randomColor = randomColor();   
} 

function flashColor() {
    for (let j=0; j<turn; j++) {
        
        for (let i=0; i<colors.length; i++) {
            
        if (colors[i].classList.contains(sequence[j])) {
          setTimeout(() => {
            colors[i].style.backgroundColor=anotherColor[i];
          },(j+1)*2000)
           
             setTimeout(()=> {
                colors[i].style.backgroundColor=sequence[j];
            },(j+2)*2000)
        }
    }
}
    
}

function getRandomColor() {
    let randomColors = [
        'red',
        'blue',
        'yellow',
        'green'
    ];
    return randomColors[parseInt(Math.random() * randomColors.length)];
};

function handleClick () {

}



  //   starting the game
  // random color generated by computer
  // winning the game

  //other function
  //game winning or lost by while loop, if === function
  //restart the level/score back to 0