/*----- constants and lets -----*/
const startButton = document.querySelector('button');
const colors = document.querySelectorAll('.tile');
const scoreCounter = document.querySelector('.score');
const board = document.querySelector('#board');
let score = 0;
let computerSequence = [];
let playerSequence =[]; 
let anotherColor = [
    "lightPink",
    "skyBlue",
    "lightYellow",
    "lightGreen"
];

/*----- event listeners -----*/
//start button  click
startButton.addEventListener('click', startGame);
colors.forEach((color, idx) => {
    color.addEventListener("click", handleColorClick);
})

/*----- functions -----*/
//Next level
// Initialize the game
function startGame() {
    score = 0;
    scoreCounter.innerHTML = `Score:${score}`;
    computerSequence = [];
    playerSequence = [];
    colors[0].style.backgroundColor = "red"; 
    colors[1].style.backgroundColor = "blue";
    colors[2].style.backgroundColor = "yellow";
    colors[3].style.backgroundColor = "green"; 
    turn = 1;
    computerSequence.push(getRandomColor());
    flashColor() 
    //randomColor = randomColor();   
} 

function handleColorClick(evt) {
   const playerGuess = evt.target.classList[0];
   playerSequence.push(playerGuess);
   console.log(playerSequence);
   if (computerSequence.length === playerSequence.length) {
    compareSequences();
   }
}
//random color generated by computer
function flashColor() {
    for (let j=0; j<turn; j++) {
        for (let i=0; i<colors.length; i++) {    
        if (colors[i].classList.contains(computerSequence[j])) {
          setTimeout(() => {
            colors[i].style.backgroundColor=anotherColor[i];
          },(j+1)*800)
             setTimeout(()=> {
                colors[i].style.backgroundColor=computerSequence[j];
            },(j+1)*1000)
        }
    }
}    
}
//function for the next sequence if it could go through or not
function compareSequences() {
    let correct = 0
    for(let j=0; j<playerSequence.length; j++) {
        if (computerSequence[j] !== playerSequence[j]) {
            scoreCounter.innerHTML = `Score:${score} Play again!`;
            break;
        } else {
            correct++
        }
    } 
    if (correct === computerSequence.length) {
    score++;
    scoreCounter.innerHTML = `Score:${score}`;
    console.log(computerSequence);
    console.log(playerSequence);
    playerSequence = [];
    computerSequence.push(getRandomColor());
    turn++;
    flashColor()
    }
}

function getRandomColor() {
    let randomColors = [
        'red',
        'blue',
        'yellow',
        'green'
    ];
    return randomColors[parseInt(Math.random() * randomColors.length)];
};



