/*----- constants and lets -----*/
const startButton = document.querySelector('button');
const colors = document.querySelectorAll('.tile');
const scoreCounter = document.querySelector('input');
const board = document.querySelector('#board');
const followingSequence = () => {
    let random = Math.floor(Math.random() * 4) + 1;
}
let startScore = 0;
let computerSequence = [];
let playerSequence =[]; 
let anotherColor = [
    "lightPink",
    "skyBlue",
    "lightYellow",
    "lightGreen"
];

/*----- event listeners -----*/
//start button  click
startButton.addEventListener('click', startGame);
colors.forEach((color, idx) => {
    color.addEventListener("click", handleColorClick);
})



/*----- functions -----*/
//Next level
// Initialize the game
function startGame() {
    startScore.scoreCounter = 0;
    computerSequence = [];
    playerSequence = [];
    colors[0].style.backgroundColor = "red"; 
    colors[1].style.backgroundColor = "blue";
    colors[2].style.backgroundColor = "yellow";
    colors[3].style.backgroundColor = "green"; 
    turn = 1;
    computerSequence.push(getRandomColor());
    flashColor() 
    //randomColor = randomColor();   
} 

function handleColorClick(evt) {
   const playerGuess = evt.target.classList[0];
   playerSequence.push(playerGuess);
   console.log(playerSequence);
   if (computerSequence.length === playerSequence.length) {
    compareSequences();
   }
}
//random color generated by computer
function flashColor() {
    for (let j=0; j<turn; j++) {
        for (let i=0; i<colors.length; i++) {    
        if (colors[i].classList.contains(computerSequence[j])) {
          setTimeout(() => {
            colors[i].style.backgroundColor=anotherColor[i];
          },(j+1)*800)
             setTimeout(()=> {
                colors[i].style.backgroundColor=computerSequence[j];
            },(j+1)*1000)
        }
    }
}    
}

function compareSequences() {
    if (computerSequence.length === playerSequence.length) {
        scoreCounter.score++;
        playerSequence = [];
    
    } else {
        score = 0;

    }

}

function getRandomColor() {
    let randomColors = [
        'red',
        'blue',
        'yellow',
        'green'
    ];
    return randomColors[parseInt(Math.random() * randomColors.length)];
};




  
  // random color generated by computer
  // winning the game

  //other function
  //game winning or lost by while loop, if === function
  //restart the level/score back to 0